/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_A_FILES           12
#define MMAP_ASSETS_A_CHECKSUM        0xD357

enum MMAP_ASSETS_A_LISTS {
    MMAP_ASSETS_A_BLINKING_AAF = 0,        /*!< Blinking.aaf */
    MMAP_ASSETS_A_WHOLE_ELF_AAF = 1,        /*!< Whole_elf.aaf */
    MMAP_ASSETS_A_BELL_AAF = 2,        /*!< bell.aaf */
    MMAP_ASSETS_A_COOKIE_AAF = 3,        /*!< cookie.aaf */
    MMAP_ASSETS_A_CROSS_AAF = 4,        /*!< cross.aaf */
    MMAP_ASSETS_A_CROSS2_AAF = 5,        /*!< cross2.aaf */
    MMAP_ASSETS_A_HAPPY_AAF = 6,        /*!< happy.aaf */
    MMAP_ASSETS_A_HAPPY2_AAF = 7,        /*!< happy2.aaf */
    MMAP_ASSETS_A_HEART_AAF = 8,        /*!< heart.aaf */
    MMAP_ASSETS_A_SLEEP_AAF = 9,        /*!< sleep.aaf */
    MMAP_ASSETS_A_SNOWMAN_AAF = 10,        /*!< snowman.aaf */
    MMAP_ASSETS_A_STAR_AAF = 11,        /*!< star.aaf */
};
