/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_EMOJI_FILES           12
#define MMAP_EMOJI_CHECKSUM        0x508F

enum MMAP_EMOJI_LISTS {
    MMAP_EMOJI_BLINKING_AAF = 0,        /*!< Blinking.aaf */
    MMAP_EMOJI_WHOLE_ELF_AAF = 1,        /*!< Whole_elf.aaf */
    MMAP_EMOJI_BELL_AAF = 2,        /*!< bell.aaf */
    MMAP_EMOJI_COOKIE_AAF = 3,        /*!< cookie.aaf */
    MMAP_EMOJI_CROSS_AAF = 4,        /*!< cross.aaf */
    MMAP_EMOJI_CROSS2_AAF = 5,        /*!< cross2.aaf */
    MMAP_EMOJI_HAPPY_AAF = 6,        /*!< happy.aaf */
    MMAP_EMOJI_HAPPY2_AAF = 7,        /*!< happy2.aaf */
    MMAP_EMOJI_HEART_AAF = 8,        /*!< heart.aaf */
    MMAP_EMOJI_SLEEP_AAF = 9,        /*!< sleep.aaf */
    MMAP_EMOJI_SNOWMAN_AAF = 10,        /*!< snowman.aaf */
    MMAP_EMOJI_STAR_AAF = 11,        /*!< star.aaf */
};